-- FINAL Employee Insert Script
-- Run this in Supabase SQL Editor after setting up the database schema
-- Total: ~202 employees across all departments

-- Lamb BR employees (37 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Bui, Thi Hong Luu', '6731', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '316', '2020-01-01'),
('Chen, Li Hong', '6616', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Dinh, Minh Tam', '6754', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Harijono, Chyntia', '6855', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('He, Wujie (Jay)', '6548', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '172', '2020-01-01'),
('Ho, Huynh Thien Kim (Kimmie)', '6361', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '348', '2020-01-01'),
('Hoang, Vu Diep (David)', '6457', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Huynh, Cong Hau (David)', '6759', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '373', '2020-01-01'),
('Jin, Xiaolin (Joy)', '3723', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '318', '2020-01-01'),
('Kong, Kathleen', '6273', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Lai, Yunrong (Allan)', '6693', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '155', '2020-01-01'),
('Li, Tao (Terry)', '6549', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '152', '2020-01-01'),
('Lin, Wenqiang (Lynn) - 482', '3724', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Lo, Thi Nhung (Anna)', '6571', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '323', '2020-01-01'),
('Lu, Chia Hui (Jenny)', '6812', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Ngo, Hoang Kai', '6741', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Dang Vuong (Olwen)', '6363', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '156', '2020-01-01'),
('Nguyen, Minh Dai (Danny)', '6321', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Pham, Phuoc Man', '6755', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Pham, Van Phuoc (John)', '6572', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Renmei, Li (Jelly)', '6526', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Sam, Van Toan (Gary)', '6482', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '368', '2020-01-01'),
('Shao, Yi Ting (Olivia)', '6668', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Song, Vinh', '6353', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '382', '2020-01-01'),
('Thai, Thi Tra Giang', '6607', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '347', '2020-01-01'),
('Tran, Linh Duy', '6604', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Tran, Thanh Tuan (Joe)', '6746', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '128', '2020-01-01'),
('Tran, Thi Thanh Huong (Linda)', '6456', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '338', '2020-01-01'),
('Xu, Lijie', '6704', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '141', '2020-01-01'),
('Zhang, Dong Hai (Anson)', '6695', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '143', '2020-01-01'),
('Zhang, Mingtao (Brody)', '6792', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, '142', '2020-01-01'),
('Zhao, Chuan (Carl)', '6527', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, '369', '2020-01-01'),
('Elliott, Alex-Roy Alan James W Bale (Alex) - L5', '114', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Nguyen, Thi To Linh (Lily)', '6483', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Nguyen, Duc Huy(Peter)', '6882', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2025-12-09'),
('Barrionuevo Ramirez, Alexis Stuard', '6885', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2025-12-16'),
('Nguyen, Nguyet Hang(Felix)', '6889', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, NULL, '2025-12-23');

-- Beef BR employees (41 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Chu, Thanh Toan', '6387', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Dang, Hoang Hong Hai(Harry)', '6725', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Duong, Man Nhi (Belle)', '6662', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '344', '2020-01-01'),
('Ferolino, Christal', '6858', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '308', '2020-01-01'),
('Ha, Van Phuong (Ethan)', '6369', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Huang, Ming (Ming)', '6443', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '136', '2020-01-01'),
('Khairah, Zuhairatul (Ira)', '6716', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '511', '2020-01-01'),
('Lai, Han Thi Ngoc (Hannah)', '6357', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Le, Quoc Duc', '6777', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Lin, Ting (Christine)', '6692', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Lin, Yongshuang (Amy)', '6789', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '337', '2020-01-01'),
('Liu, Xiaoli', '6629', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Ngeoh, Kuan Poh', '6515', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Nguyen, Hoang Tung', '6743', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Kieu Dan Thanh (Dani)', '6763', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '305', '2020-01-01'),
('Nguyen, Le Tuyet Nhut (May)', '6727', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Ngoc Huong', '6757', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Nu Tram Nhi (Dorris)', '6359', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '349', '2020-01-01'),
('Nguyen, Thi Diem Suong (Joe)', '6669', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '345', '2020-01-01'),
('Nguyen, Thi Mai Tram (Vivian)', '6355', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '501', '2020-01-01'),
('Nguyen, Thi Ngoc Bich (Selina)', '6659', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '313', '2020-01-01'),
('Nguyen, Thi Ngoc Linh (Linh)', '6764', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '327', '2020-01-01'),
('Nguyen, Thi Yen (Angela)', '6461', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '353', '2020-01-01'),
('Nguyen, Thuy Thanh Vy', '6724', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '343', '2020-01-01'),
('Nguyen, Trang Bao Ngoc', '6639', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '505', '2020-01-01'),
('Nguyen, Trong Nghia (Seven)', '6761', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nurhalza, Nadia (Nad)', '6717', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '504', '2020-01-01'),
('Phan Thi Thu Hien', '6842', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '307', '2020-01-01'),
('Pei, Xiang', '6824', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Cao Quoc Loc (Leo)', '6360', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Tran, Hoang Phuc', '6747', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '140', '2020-01-01'),
('Tran, Thanh Sang (Sang)', '6508', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Thi Minh Hoai (Helia)', '6711', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, '332', '2020-01-01'),
('Tran, Thi My Loan (Loan)', '6507', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Trieu, Dinh Thi (Lucy)', '3620', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '339', '2020-01-01'),
('Wang, Yuanjie (Geron)', '6681', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '135', '2020-01-01'),
('Yang, Hongcai', '6628', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, '138', '2020-01-01'),
('Tuliau, Samasoni', '6875', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2025-12-02'),
('Vu, Manh Hung(Felix)', '6884', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2025-12-09'),
('Bui, Huy Kien(Lucas)', '6880', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2025-12-09'),
('Phan, Van Duc Nhat(Jiro)', '6886', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, NULL, '2025-12-16');

-- Cold Store employees (16 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Bhebhe, Leslie', '6833', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Darmanin, Brandyn', '6847', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, '145', '2020-01-01'),
('Hempstead, Trevor', '6836', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Kayden, Kirby-Wilson', '6857', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Liu, Yu Kuei (Chris)', '6679', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Mai Xuan Nghi', '6760', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, '355', '2020-01-01'),
('Mohd Faisal, Saifulnizam', '3857', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Van Quang (Wang)', '6677', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Parsons, Roland', '6859', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Peterson Daniel', '6844', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Pham The Dat', '6841', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, '364', '2020-01-01'),
('Romuar, Marc Ericson Samson', '6632', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tju, Chandra Winata (Roy)', '6493', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Quinn, Rory', '6878', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2025-12-01'),
('Padilla, Dominic Gerold', '6888', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2025-12-22'),
('Nguyen, Thanh Tien(Tien)', '6890', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, NULL, '2025-12-22');

-- Kill Floor employees (70 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Baleilakeba, Bulivanua Cerevakarua', '6786', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Bao, Quang Ja Sin', '6608', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Bolavucu, Lanieta', '6405', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, '734', '2020-01-01'),
('Brown, Mesake', '6770', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Budde, Troy', '198', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Bui, Huu Hoang (Tom)', '6356', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Bui, Quoc Cuong (Vincent)', '6660', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Dinati, Petero', '6772', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Dinh, Thi Tuyet Trinh (Clara)', '6748', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Dinh, Van Hong', '6362', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Do, Huu Phung (Ryan)', '6745', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Drua, Filimone', '6776', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Duong, Thi My Huong (Cherry)', '6559', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Erardo, Charish Coton', '6850', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Faalelei, Savali', '6793', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Ha, Van Binh', '6637', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Hoang, Ngoc Bich Tran', '6738', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, '715', '2020-01-01'),
('Huang, Mingye', '6697', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Idris, Mohammad', '6804', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Khawari, Abdul', '3313', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Le, Triet Lam Minh', '6768', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Lu, Jianxin', '6696', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Mai, Nguyen Hoang Lam (Andre) - 482', '3820', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Nguyen, Duc Thien (Tomy)', '6661', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Hong Phuc', '6811', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Quang Chinh', '6810', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Quang Minh', '6749', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Quoc Dai', '6813', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Thach Phu', '6545', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Thi Nga', '6635', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Thi Xinh (Rose)', '6673', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, '732', '2020-01-01'),
('Nguyen, Thi Xuan Thao (Sala)', '6728', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Van Bao', '6752', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nguyen, Van Hung', '6633', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Song, Mian', '6698', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Toohey, Pauline', '469', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Tran Thi Phuong Thao', '6798', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Hoang Quan (Tony)', '6354', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Tran, Nu Hoang Thuc (Tiana)', '6726', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Thi Hai Nhien (Bella)', '6756', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Thi Yen Nhi (Nhi)', '6667', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Tran, Van Du (John)', '6672', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Van Hung', '6736', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Trieu, Thi Thuy Linh (Oscar)', '6670', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Trisani, I Gusti Ayu Mitha', '6569', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Vo, Thien Duc (Tommy)', '6573', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Waqavuna, Markira', '3452', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Wu Shengbin', '6466', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Yahya, Abdullah Bin', '6721', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Seniloli, Bulou (Va) - L3', '101', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, '709', '2020-01-01'),
('Nokasavu, Josese (Josh) - L5', '102', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Domonakibau, Peni (Ben) - L3', '110', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Cava, Aminio - L4', '121', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Tikomailepanoni, Wainimala (Mala)L3', '124', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Valadua Villiame (Bill) - L5', '125', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Vakasilimi, Jekesoni (Jekeson) - L5', '134', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Bari, Isikeli (Sike) -L4', '135', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Babacala, Mosese - L4', '137', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Talemaiiraki, Simione Pai (Simione)L4', '138', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Naivaluleve, Losalini (Losalini) -L4', '140', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Seninawanawa, Jale (Jale) -L 3', '142', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Kubu, Philomena (Philo) - L3', '109', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, '704', '2020-01-01'),
('Nguyen, Van Quyen', '6865', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-11-06'),
('Ho, Thi Thu Huyen', '6866', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-11-13'),
('Qi, Ziqin(Katrina)', '6870', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-11-24'),
('Yang, Han(Marka)', '6871', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-11-24'),
('Han, Mengping(Juddy)', '6872', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-11-24'),
('Naqeui, Waisale', '6876', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-12-01'),
('Foreqe, Vereniki(Frank)', '6881', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, NULL, '2025-12-01');

-- Loadout employees (6 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Maduka, Donatus', '2548', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, '146', '2020-01-01'),
('Murphy, Brandon', '6802', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Murphy, Matthew', '6803', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, '357', '2020-01-01'),
('Samulakai, Penaia', '6723', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Nabainivalu, Filipe - L4', '113', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, '371', '2020-01-01'),
('Patadungan,Dedi Bileam', '6887', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, NULL, '2025-12-22');

-- Rendering employees (7 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Aurum, Boyke (Boy)', '6538', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Benavente, Hector', '6342', (SELECT id FROM departments WHERE name = 'RENDERING'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Calado, Roger', '6815', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Hario, Veron', '6715', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Sapril, Sapril', '4051', (SELECT id FROM departments WHERE name = 'RENDERING'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('South, Johnathon', '4003', (SELECT id FROM departments WHERE name = 'RENDERING'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Murray, Edward William', '6848', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, NULL, '2020-01-01');

-- Skin Shed employees (9 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Bramble, Robert', '6651', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Ebrahime, Niamatullah', '6385', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Namasumasu, Sailosi', '6851', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Sobey, Glen', '3304', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Stacey Glenn', '6839', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Vakanawa, Josateki (Joe) -L3', '133', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Kalougata, Penjasi, (Pen) - L6', '106', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Neville John Liqaiula - L3', '146', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Vunimasi, Josateki (Josh)', '6873', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, NULL, '2025-11-24');

-- QA employees (12 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Le Vv, Thi My Hoa (Jean)', '3741', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Massiwa, Dzivaido', '6831', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Parsons, Ben', '1907', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Qiaqia, Vilikesa', '6832', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Rafeee, Khairunnusa (Nysa)', '6691', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Ruslan, Noor Amanina', '6664', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Tran, Thi My Linh (Chloe)', '6358', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Trotter Linda', '3667', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, '302', '2020-01-01'),
('Vo, Viet Cong', '6852', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('Yonghong Huang', 'Yonghong Huang', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Nina Fouwana Drua', '6215', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Quinn, Aaron', '6868', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, NULL, '2025-11-20');

-- Maintenance employees (4 total)
INSERT INTO employees (name, english_name, department_id, employment_status, locker_number, start_date) VALUES
('Buckinham, Tim', '6523', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Davis, Sam', '6413', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, NULL, '2020-01-01'),
('Jennings, Trae John', '6819', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'CASUAL'::employment_status, NULL, '2020-01-01'),
('White, Nigel', '3852', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, NULL, '2020-01-01');

-- All done!
-- Total employees inserted: ~202
