-- Insert all employees with payroll numbers, employment status, and wage status
-- C = Casual, F = Full Time, S = Salary/Full Time
-- LH = Labor Hire (Full Time but under Labor Hire wage status)
-- Note: english_name field is left as NULL (will be filled manually if needed)

-- LAMB BR EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6885', 'Barrionuevo Ramirez, Alexis Stuard', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6731', 'Bui, Thi Hong Luu', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6616', 'CHEN, LI HONG', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6855', 'Harijono, Chyntia', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6548', 'HE, WUJIE (JAY)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6361', 'HO, HUYNH THIEN KIM (KIMMIE)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6457', 'Hoang, Vu Diep (David)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6759', 'HUYNH, CONG HAU (DAVID)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('3723', 'JIN, XIAOLIN (JOY)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6273', 'KONG, KATHLEEN', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6693', 'LAI, YUNRONG (ALLAN)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('1', 'Legaspi, Charlene', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6526', 'LI, RENMEI (JELLY)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6549', 'LI, TAO (TERRY)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('3724', 'LIN, WENQIANG (LYNN) - 482', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6571', 'Lo, Thi Nhung (Anna)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6812', 'Lu, Chia Hui (Jenny)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6363', 'NGUYEN, DANG VUONG (OLWEN)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6882', 'Nguyen, Duc Huy(Peter)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6889', 'Nguyen, Nguyet Hang(Felix)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6483', 'NGUYEN, THI TO LINH  (LILY)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6755', 'PHAM, PHUOC MAN', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6572', 'Pham, Van Phuoc (John)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6482', 'SAM, VAN TOAN (GARY)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6668', 'SHAO, YI TING (OLIVIA)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6353', 'SONG, VINH', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6607', 'THAI, THI TRA GIANG', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6604', 'TRAN, LINH DUY', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6746', 'TRAN, THANH TUAN (JOE)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6456', 'TRAN, THI THANH HUONG (LINDA)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6704', 'Xu, Lijie', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6695', 'Zhang, Dong Hai (Anson)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6792', 'Zhang, Mingtao (Brody)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6527', 'ZHAO, CHUAN (carl)', (SELECT id FROM departments WHERE name = 'LAMB_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01');

-- BEEF BR EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6880', 'Bui, Huy Kien(Lucas)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6387', 'Chu, Thanh Toan', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6725', 'Dang, Hoang Hong Hai', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6742', 'DUONG, DANH KAI', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6662', 'Duong, Man Nhi (Belle)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6858', 'Ferolino, Christal', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6369', 'HA, VAN PHUONG (ETHAN)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6443', 'HUANG, MING (MING)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6716', 'Khairah, Zuhairatul (Ira)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6357', 'LAI, HAN THI NGOC (HANNAH)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6692', 'LIN, TING (CHRISTINE)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6789', 'Lin, Yongshuang (Amy)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6629', 'Liu, Xiaoli', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6515', 'NGEOH, KUAN POH', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6763', 'Nguyen, Kieu Dan Thanh (Dani)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6727', 'Nguyen, Le Tuyet Nhut (May)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6757', 'NGUYEN, NGOC HUONG', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6359', 'NGUYEN, NU TRAM NHI (DORRIS)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6669', 'Nguyen, Thi Diem Suong (Joe)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6355', 'NGUYEN, THI MAI TRAM (VIVIAN)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6659', 'Nguyen, Thi Ngoc Bich (Selina)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6764', 'Nguyen, Thi Ngoc Linh (Linh)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6461', 'Nguyen, Thi Yen (Angela)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6724', 'Nguyen, Thuy Thanh Vy', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6639', 'Nguyen, Trang Bao Ngoc', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6761', 'NGUYEN, TRONG NGHIA (SEVEN)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6717', 'Nurhalza, Nadia (Nad)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6824', 'Pei, Xiang', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6842', 'Phan Thi Thu Hien', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6886', 'Phan, Van Duc Nhat(Jiro)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6360', 'TRAN, CAO QUOC LOC (LEO)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6508', 'Tran, Thanh Sang (SANG)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6711', 'Tran, Thi Minh Hoai (Helia)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6507', 'Tran, Thi My Loan (LOAN)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('3620', 'TRIEU, DINH THI (LUCY)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6875', 'Tuliau, Samasoni', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6884', 'Vu, Manh Hung(Felix)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6681', 'Wang, Yuanjie (Geron)', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6628', 'Yang, Hongcai', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('114', 'Elliott, Alex-roy Alan James W Bale (Alex) - L5', (SELECT id FROM departments WHERE name = 'BEEF_BR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01');

-- COLD STORE EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6856', 'Gleeson, Jamie', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6857', 'Kayden, Kirby-Wilson', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6679', 'LIU, YU KUEI (CHRIS)', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('3857', 'MOHD FAISAL, SAIFULNIZAM', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6890', 'Nguyen, Thanh Tien(Tien)', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6677', 'Nguyen, Van Quang (Wang)', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6888', 'Padilla, Dominic Gerold', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6859', 'Parsons, Roland', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6887', 'Patadungan,Dedi Bileam', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6841', 'Pham The Dat', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6878', 'Quinn, Rory', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6632', 'Romuar, Marc Ericson Samson', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6493', 'TJU, CHANDRA WINATA (ROY)', (SELECT id FROM departments WHERE name = 'COLD_STORE'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01');

-- LOADOUT EMPLOYEES (Note: Department might be LOADOUT based on your data)
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6523', 'Buckinham, Tim', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6413', 'DAVIS, SAM', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6819', 'Jennings, Trae John', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('3852', 'WHITE, NIGEL', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('2548', 'Maduka, Donatus', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6760', 'Mai, Xuan Nghi', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6802', 'Murphy, Brandon', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6803', 'Murphy, Matthew', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6844', 'Peterson Daniel', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6723', 'Samulakai, Penaia', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('113', 'Nabainivalu, Filipe - L4', (SELECT id FROM departments WHERE name = 'LOADOUT'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01');

-- KILL FLOOR EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6786', 'Baleilakeba, Bulivanua Cerevakarua', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6608', 'Bao, Quang Ja Sin', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6405', 'Bolavucu, Lanieta', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6770', 'Brown, Mesake', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('198', 'Budde, Troy', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6356', 'BUI, HUU HOANG (TOM)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6660', 'Bui, Quoc Cuong (Vincent)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6772', 'Dinati, Petero', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6748', 'DINH, THI TUYET TRINH (CLARA)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6362', 'DINH, VAN HONG', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6745', 'DO, HUU PHUNG (RYAN)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6776', 'Drua, Filimone', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6559', 'Duong, Thi My Huong (Cherry)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6850', 'Erardo, Charish Coton', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6793', 'Faalelei, Savali', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6881', 'Foreqe, Vereniki(Frank)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6637', 'Ha, Van Binh', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6872', 'Han, Mengping (Judy)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6866', 'Ho, Thi Thu Huyen', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6738', 'Hoang, Ngoc Bich Tran', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6697', 'Huang, Mingye', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6804', 'Idris, Mohammad', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('3313', 'Khawari, Abdul', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6696', 'Lu, Jianxin', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('3820', 'Mai, Nguyen Hoang Lam (Andre) - 482', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6876', 'Naqeui, Waisale', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6661', 'Nguyen, Duc Thien (Tomy)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6811', 'Nguyen, Hong Phuc', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6749', 'NGUYEN, QUANG MINH', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6813', 'Nguyen, Quoc Dai', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6545', 'Nguyen, Thach Phu', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6635', 'Nguyen, Thi Nga', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6673', 'Nguyen, Thi Xinh (Rose)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6728', 'Nguyen, Thi Xuan Thao (Sala)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6752', 'NGUYEN, VAN BAO', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6633', 'Nguyen, Van Hung', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6865', 'Nguyen, Van Quyen', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6870', 'Qi, Ziqin (Katrina)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6698', 'Song, Mian', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('469', 'Toohey, Pauline', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6798', 'Tran Thi Phuong Thao', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6354', 'Tran, Hoang Quan (Tony)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6726', 'Tran, Nu Hoang Thuc (Tiana)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6667', 'Tran, Thi Yen Nhi (NHI) ', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6672', 'Tran, Van Du (John)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6736', 'Tran, Van Hung', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6670', 'Trieu, Thi Thuy Linh (Oscar)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6569', 'Trisani, I Gusti Ayu Mitha', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6573', 'Vo, Thien Duc (Tommy)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6852', 'Vo, Viet Cong', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('3452', 'Waqavuna, Markira', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6466', 'Wu Shengbin', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6721', 'Yahya, Abdullah Bin ', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6871', 'Yang, Han (Marka)', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('109', 'Kubu, Philomena (Philo) - L3', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('111', 'Ranawakana, Mosese (Moji) - L7', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('101', 'Seniloli, Bulou (Va) - L3', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('102', 'Nokasavu, Josese (Josh) - L5', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('110', 'Domonakibau, Peni (Ben) - L3', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('121', 'Cava, Aminio  - L4', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('124', 'Tikomailepanoni, Wainimala (Mala)L3', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('125', 'Valadua Villiame (Bill) - L5', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('134', 'Vakasilimi, Jekesoni (Jekeson) - L5', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('137', 'Babacala, Mosese - L4', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('138', 'Talemaiiraki, Simione Pai (Simione)L4', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('140', 'Naivaluleve, Losalini (Losalini) -L4', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('142', 'Seninawanawa, Jale (Jale) -L 3', (SELECT id FROM departments WHERE name = 'KILL_FLOOR'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01');

-- MAINTENANCE EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6491', 'MENDOZA, JERWIN', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6488', 'MERCADO, GODFREY', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('3239', 'MILLER, ASHLEY', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6490', 'MOHAMED, JOHN', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6487', 'RINON, RICHARD ', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6546', 'SIAPO, RONALD', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6853', 'TELLEY, DENNIS', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6797', 'Thomas Vallikadan, Augustus', (SELECT id FROM departments WHERE name = 'MAINTENANCE'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01');

-- QA EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('3741', 'Le Vv, Thi My Hoa (Jean)', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6831', 'Massiwa, Dzivaido', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('1907', 'Parsons, Ben', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6832', 'Qiaqia, Vilikesa', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6868', 'Quinn, Aaron', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6691', 'Rafeee, Khairunnusa (Nysa)', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6664', 'Ruslan, Noor Amanina', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6358', 'Tran, Thi My Linh (Chloe)', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('3667', 'Trotter Linda', (SELECT id FROM departments WHERE name = 'QA'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('3721', 'Woolstencroft, Allen', (SELECT id FROM departments WHERE name = 'QA'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01');

-- RENDERING EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6538', 'Aurum, Boyke (Boy)', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6342', 'Benavente, Hector', (SELECT id FROM departments WHERE name = 'RENDERING'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6815', 'Calado, Roger', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6715', 'Hario, Veron', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6848', 'Murray, Edward William', (SELECT id FROM departments WHERE name = 'RENDERING'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('4051', 'SAPRIL, SAPRIL  ', (SELECT id FROM departments WHERE name = 'RENDERING'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('4003', 'SOUTH, JOHNATHON', (SELECT id FROM departments WHERE name = 'RENDERING'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01');

-- SKIN SHED EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6651', 'Bramble, Robert', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6385', 'EBRAHIME, NIAMATULLAH', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6851', 'Namasumasu, Sailosi', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('3304', 'SOBEY, GLEN', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6839', 'Stacey Glenn', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6873', 'Vunimasi, Josateki', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('133', 'Vakanawa, Josateki (Joe) -L3', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('106', 'Kalougata, Penjasi, (Pen) - L6', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, '2020-01-01'),
('146', 'Neville John Liqaiula - L3', (SELECT id FROM departments WHERE name = 'SKIN_SHED'), 'FULL_TIME'::employment_status, 'LABOR_HIRE'::wage_status, NULL, '2020-01-01');

-- CLEANING EMPLOYEES
INSERT INTO employees (payroll_number, name, department_id, employment_status, wage_status, locker_number, start_date) VALUES
('6269', 'AGUSTIN, ERLINDA', (SELECT id FROM departments WHERE name = 'CLEANING'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('2865', 'HODGES, JANICE - LAUNDRY', (SELECT id FROM departments WHERE name = 'CLEANING'), 'FULL_TIME'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6339', 'MAI, HANG', (SELECT id FROM departments WHERE name = 'CLEANING'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01'),
('6712', 'Sarus Raylend ', (SELECT id FROM departments WHERE name = 'CLEANING'), 'CASUAL'::employment_status, 'WFA'::wage_status, NULL, '2020-01-01'),
('6835', 'Tian, Hua', (SELECT id FROM departments WHERE name = 'CLEANING'), 'CASUAL'::employment_status, 'WFA'::wage_status, '2020-01-01');
